### ISSUE TITLE
[apis-project] Irene Lopez Lujan

### ISSUE THREAD

**Issue by IreneLopezLujan** [ironhack-datalabs/datamad0820#455]
Aquí podeis encontrar mi repositorio : https://github.com/IreneLopezLujan/pepelines-proyect3

**Comment by olmocorell** [comment]
¡¡Hola Ireneeeeeeeeeeee!! 🚀 💪 En primerito lugar, perdona porque ya ha pasado una semanita desde que hiciste este proyecto pero... ¡aquí estoy!
Te cuento cositas

### Readme 

Está muy bien, así es como se hace un readme, con su imagencita de portada, su desarrollo, el uso del markdown, la explicación de los argparse, el stack de tecnologías con la documentación, pero, sobre todo, lo que está SÚPER, es que hayas puesto un ejemplo de ejecución del programa 
Eso es TOP
<img width="521" alt="Captura de pantalla 2020-09-20 a las 17 12 17" src="https://user-images.githubusercontent.com/57899051/93714641-71a28880-fb64-11ea-9249-dd9aaf7506ad.png">

### Organización del proyecto

En principio parece que está bastante organizado, pero luego tienes archivos que se repiten en dos carpetas, tanto en src como en la carpeta de análisis... tienes `funciones_analisis_join.py`. Esto es un lío y puede generarte problemas.... 
¿Qué te propongo? En tu caso, si has hecho unos jupyter notebooks para hacer algún tipo de limpieza o pruebas, que tengas una carpeta de jupyter notebooks y que luego automatices tooooooooooooodas esas tareas que hacen los notebooks en archivos .py que hagan lo mismo cuando los ejecutas. Sé que puede parecer complicado o loco, pero no lo es. Si tienes alguna duda sobre esto, dime y lo vemos. ¿Vale?

La carpeta de data... ¿qué data contiene? me refiero, estaría bien poder diferenciar el data que es input y sin tratar, de los csv limpios o enriquecidos que pueda generar tu proyecto. 

### Jupyter notebooks

¡Ojo! ¡Cuidado con los prints infinitos pliiiiiiiiis! Por ejemplo en [este](https://github.com/IreneLopezLujan/pepelines-proyect3/blob/master/2.An%C3%A1lisis_e_uniones_datos/analisis_join.ipynb) o en [este](https://github.com/IreneLopezLujan/pepelines-proyect3/blob/master/1.Web%26Api_scraping/Scraping_api_vivino_SINUTILIZAR.ipynb), que aunque no lo llegues a utilizar, está ahí y yo he entrado a ver qué había y.... 💣 

### Archivos de funciones

En primerito lugar... ojo con importar un montón de módulos que no necesitamos en el archivo de funciones.
<img width="896" alt="Captura de pantalla 2020-09-20 a las 17 34 57" src="https://user-images.githubusercontent.com/57899051/93715121-9ba97a00-fb67-11ea-97e6-cefd314a569b.png">

### Funciones

Las funciones en sí no están mal, aunque solo has documentado una. Intenta documentarlas todas ¿vale?.
Luego, ¡estas están súper! 🔝 

<img width="788" alt="Captura de pantalla 2020-09-20 a las 17 39 42" src="https://user-images.githubusercontent.com/57899051/93715202-45890680-fb68-11ea-95e3-89fe612844e4.png">

### Main.py
¿Qué pasó aquí? Me haces unas funciones súper top que validan los colores del vino y la comida y tal....pero... ¡¡no las usas!! lo ideal sería meterlas como type en el argparse. Sería redondo.
<img width="1174" alt="Captura de pantalla 2020-09-20 a las 17 40 36" src="https://user-images.githubusercontent.com/57899051/93715223-65b8c580-fb68-11ea-8ea5-9fedddd2cd73.png">

Por otra parte, entiendo el concepto del proyecto, entiendo algunas de las cosas que haces....pero me falta el nexo de unión. Hay algunos jupyters que hacen cosas...pero ejecuto el main.py en mi ordenador con el ejemplo de ejecución que propones y no pasa nada. No me devuelve ninguna info...¿Sigues trabajando en ello? Bueno, veo que el último commit ha sido hace 4 horitas así que me imagino que sí.
Bueno, si tienes alguna duda de lo que sea o necesitas alguna orientación para terminar el proyecto o terminar de atar cabos sueltos... me dices ¿vale?

Espero que estés disfrutando de este finde "libre" ¡¡seguimos a topeeeeeeeeeeeeeeee!! 💪 🚀 

![5662f68ac6e6b60877acdec830dc491e](https://user-images.githubusercontent.com/57899051/93715356-0c04cb00-fb69-11ea-8347-71c4a90c5cf4.jpg)

**Comment by IreneLopezLujan** [comment]
Holaaa Amanda!! 

Mil gracias por todos los comentatios, que parece que no pero me ayudan muchisimo. 

Hoy he estado tocando cosas y en efecto, no consigo que termine de funcionar y tengo muchas dudas, que si podemos ver mañana antes de partir las clases pues seria un alivio, porque creo que hay cosas que no he entendido bien. 

¡Buen domingo!
