### ISSUE TITLE
[apis-project] Paula Nuno

### ISSUE THREAD

**Issue by PaulaNuno** [ironhack-datalabs/datamad0820#456]
Hola, chicos,

Esta es la URL del proyecto de esta semana
https://github.com/PaulaNuno/apis-project

Muchas gracias,
Paula

**Comment by olmocorell** [comment]
¡Hola guajaaaaaaaaaa! 🚀 💪 
En primerito lugar, perdona por haber venido a corregir este proyecto una semana más tarde... pero bueno ¡aquí estoy! que es lo importante, supongo 😄 
Y dicho esto, te cuento cositas del proyecto:

### Readme

A ver está bastante bien Pauli, y mola que tengas enlaces a otras partes de tu proyecto, peeeeero, me falta:
- Un ejemplo de ejecución del main.py (que ahora hablamos de la que me has liado con eso)
- Un pequeño resumen del stack de tecnologías que utilizas con enlaces a la documentación de dichas tecnologías. 

### Organización del proyecto

A ver, echemos un ojo:
<img width="938" alt="Captura de pantalla 2020-09-20 a las 18 31 01" src="https://user-images.githubusercontent.com/57899051/93716324-702a8d80-fb6f-11ea-8111-b332d5675f7b.png">
Los jupyter notebooks los puedes meter en una carpeta de "notebooks"
Por otra parte.....   ⚠️  ¿Dónde están tus archivos de funciones? ⚠️  🔥 
Y por último, el csv, debería ir en una carpeta aparte llamada input/data o como quieras.

### Jupyter notebooks

A ver prima, ¿[este](https://github.com/PaulaNuno/apis-project/blob/master/web_scraping_procedure.ipynb) print infinito? 
Entiendo que ese jupyter lo usas para hacer web scraping y [este](https://github.com/PaulaNuno/apis-project/blob/master/reports.ipynb) otro es en el que tienes el dataset original que luego quieres enriquecer. 
Vale, no está mal que hagamos las cosas para probar cosas en un jupyter notebook pero luego, en este proyecto, lo que teníamos que hacer era pasar todo a archivos de funciones...en este caso no tienes ninguna función ni ningún .py de funciones de ningún tipo... jo ¿y eso? 

### Main.py 

¿Qué ha pasado aquí Pauli? tienes un main.py pero que realmente es un jupyter notebook .... pero está en .py, pero por dentro tiene la forma de código que tienen los jupyter notebooks.... no entiendo nada. ¿Qué has hecho aquí?
En este caso no puedo felicitarte, porque creo que realmente no has entendido bien lo que se pedía en el proyecto...y no tienes un main.py que podamos ejecutar con argparse.... pero bueno, si tienes alguna duda al respecto me dices... ¿vale? 
Es importante que entendamos la diferencia entre los .py y los jupyter notebook y usemos ficheros .py que podamos ejecutar porque fuera de aquí, aunque también se usan los jupyter, es un entorno que se usa para hacer pruebas, después, siempre todo lo vamos a poner en ficheros, y además, en el proyecto final también lo vas a tener que hacer así...

Así que en ese sentido tengo que decirte que tu proyecto está un poco a medias, aunque está muy bien que te hayas peleado con el web scraping.... 
¡Venga PauliiiiiiiiiII! Espero que este finde sin proyecto le hayas pegado duro a Python, ya sabes que estoy aquí para cualquier cosa que necesites.

![unnamed2](https://user-images.githubusercontent.com/57899051/93742709-e1f5ec00-fbee-11ea-8974-9122b09682ab.png)
