### ISSUE TITLE
[apis-project] Silvia Hernandez

### ISSUE THREAD

**Issue by silviaherf** [ironhack-datalabs/datamad0820#457]
https://github.com/silviaherf/apis-project

Estoy basante satisfecha, aunque en el main podría haber limpiado la parte de las conclusiones (los gráficos y demás) con una función aparte, pero no me ha dado tiempo!! Los gráficos no salen de los argparse porque no tendría sentido el análisis si no.. ya lo  hablamos

**Comment by ferrero-felipe** [comment]
Muy bien, Silvia! :rocket:
Me alegro que te haya gustado hacer el proyecto!
Te voy comentando unas cosas mientras lo reviso. 
No subas la carpeta zz_trash. Ponle en el `.gitignore`.
El readme, :top:! Información necesaria, clara, organizada.
Igualmente el reporte que haces en pdf. :)
Considera que puedes abstraer más el `main.py`, separando el codigo en diferentes ficheros, el argparse, por ejemplo. No pasa nada que los ficheros de codigo sean cortitos. Nada más que el necesario en cada parte deja el codigo más sencillo a quien le vea. Jejeje
Con la practica ya verás que te resultará lo mismo tener todo en un fichero que en muchos. :)
Muy bien los modulos de funciones, documentadas, organizadas! Perfect! :rocket:
Llegar al punto de enviar un correo no es fácil! Enhorabuena por el proyecto.

Muy buen trabajo!

![image](https://user-images.githubusercontent.com/52798316/94030062-ae1cf100-fdbd-11ea-9fa6-d9e64071d73f.png)
