### ISSUE TITLE
[apis-project] Borja Llanos

### ISSUE THREAD

**Issue by grundius1** [ironhack-datalabs/datamad0820#458]
el link del repo:
https://github.com/grundius1/apis-project

Un saludo

**Comment by ferrero-felipe** [comment]
Muy bien, Borja! :rocket:
Super :top: que hayas construido el argparse para aceptar diferentes combinaciones de argumentos y que se puedan poner multiples argumentos para cada parametro! Eso es muy buena practica! Programas listos para cualquier cosa. 
Podrias definir el arparse a parte, simplemente porque es razonablemente largo y podriamos dejar main más sencillo. En el objetivo de que sea bastante modular la lectura. :)
Lo que no entiendo es por qué luego tienes inputs en las funciones de api calls, podrias ser un parametro via argparse tambien.
Super guay que hayas validado los datos con tus funciones!


Muy buen trabajo!


Te pongo ese meme y espero que sea bueno, pero yo absolutamente no entiendo LOL
![image](https://user-images.githubusercontent.com/52798316/94424056-e2136000-0189-11eb-8156-d229c28f34b7.png)
