### ISSUE TITLE
[apis-project] David Lazaro

### ISSUE THREAD

**Issue by Davidlazarog** [ironhack-datalabs/datamad0820#459]
Os dejo el link de mi repo! 

https://github.com/Davidlazarog/API-Proyect-Pokemon

Travesura realizada!
![image](https://user-images.githubusercontent.com/68644448/93110488-ad95a380-f6b5-11ea-970f-4d640990c2a1.png)

**Comment by ferrero-felipe** [comment]
Muy bien, David! :rocket:
Genial el gif en el readme!!! Super chulo. No obstante, te faltan las instrucciones de ejecución del programa, otras cositas más que quieras poner, etc.
No llames los argumentos del argparse en mayuscula, mantenemos aqui la misma convención que en cualquier codigo python y les llamamos en minuscula.
Muy bien tener diferentes ejecuciones del programa dependiendo de los inputs que se ejecuten y los argumentos mutuamente excluyentes.
Mucho cuidado con los imports!!!! Nada de copy paste.
Solo importes en cada fichero lo que necesites. Importas un monton de funciones que no llegas a usar. 
Y, como regla general, no importamos los modulos dentro de las funciones!
![image](https://user-images.githubusercontent.com/52798316/94425066-92359880-018b-11eb-84f3-cdb899ea6103.png)
Eso huele mucho a dicionario.
Defines dos funciones para sacar el peso y la altura del pokemon, pero luego no las usas. Y menos mal que no las usas, pues serian dos peticiones más a la api sin necesidad.

Muy buen trabajo!

![image](https://user-images.githubusercontent.com/52798316/94425307-02441e80-018c-11eb-851b-e0f3f3e31be8.png)
