### ISSUE TITLE
[apis-project] Raul Fernandez

### ISSUE THREAD

**Issue by rfminguez** [ironhack-datalabs/datamad0820#460]
Hola,

Os dejo la url del proyecto del fin de semana:
https://github.com/rfminguez/w4_api_project.git

Un saludo.

**Comment by olmocorell** [comment]
¡¡Hola Raúúúúúúúúúú!! en primerito lugar perdona por venir a estas alturas a corregir el proyecto. Siento haber tardado tanto.
Te cuento cositas

### Readme

Está perfecto, un readme que invita a seguir leyendo el resto del código. Está genial, enhorabuena.

### Organización de los archivos

Te diría que los jupyter los metas en una carpeta de notebooks más organizados y no estén por ahí en medio del repo, que está bastante bien organizadito. 😄 

### Main.py

Aquí has hecho un poco de trampas, ahora que te has peleado con la Api y la estructura de archivos, esto te parecerá súper fácil realmente, pero tienes un montón de funciones definidas en el main.py que puedes definir en otros archivos y llamar directamente desde el main() porque... este fichero no podía contener más de 100 líneas, y... ya te digo yo que se puede resolver con muchas menos!.

¿Y todos estos if?
<img width="663" alt="Captura de pantalla 2020-09-29 a las 23 03 45" src="https://user-images.githubusercontent.com/57899051/94615437-08c7b880-02a8-11eb-8b5a-082dac14c9f2.png">
Seguro que hay una función que se puede parametrizar para que en función de lo que entre haga el get... ¿entiendes lo que te digo?

### Archivos de funciones

Por una parte te diré que las funciones y clases de restaurant.py están súúúúúúúúúper y el código es bastante eficiente.
Pero ¿qué pasa aquí?
Aquí hemos "repetido" un montón de código...no está mal que hagamos funciones largas siempre y cuando sean funciones generalistas y con un propósito, en este caso, hay muchas funciones que hacen prácticamente lo mismo pero solo cambia el parámetro... podemos ¡parametrizar!
<img width="1063" alt="Captura de pantalla 2020-09-29 a las 23 33 49" src="https://user-images.githubusercontent.com/57899051/94618904-3c0c4680-02ac-11eb-888f-ad32fef1ebf3.png">

Pero bueno, enhorabuena por tu proyecto, has hecho un buen trabajo. Cualquier cosa que quieras comentar sobre el código ya sabes dónde encontrarme.
¡¡Sigue así Raúl!!


![w3hb2plmwcep5epvx6w4h1q7hwrhvtlk0fwsdcrrbj3boumtj34qmvfbfq2uvg2](https://user-images.githubusercontent.com/57899051/94621330-5d6f3180-02b0-11eb-8f13-9b761bb0e177.jpg)
