### ISSUE TITLE
[apis-project] Juan Mena

### ISSUE THREAD

**Issue by jmena23** [ironhack-datalabs/datamad0820#461]
Link al repo: https://github.com/jmena23/APIs-Project

**Comment by olmocorell** [comment]
¡¡Hola Juaaaaaaaaaaaaaan!! En primer lugar te pido disculpas por haber tardado tanto en venir a corregir este proyecto. 
Bueno, ¡te cuento cositas!

### Readme 

Enhorabuena, está súper bien, lo único que le añadiría para que fuera perfecto es un ejemplo de cómo se ejecuta el código principal con los argparse y los flags... tipo `python3 main.py -t 'BOS' etc`. 
Incluir esto está genial, por si alguien quiere descargarse tu repo e incluso ejecutarlo en su ordenador para probar el programa. 

### Organización de archivos

Está genial, lo único que el jupyter notebook que tienes fuera, a la altura del readme lo metería en una carpeta, o bien en src, o bien en otra de "limpieza" o de "notebooks", así puedes tener más de uno para hacer pruebas o cosas que necesites.

### Main.py

A ver.... ¡¡WHAT A MARAVILLA!! Enhorabuena, esto es lo que se pedía, así es como se hace un main.py, un hilo de ejecución limpio llamando a otras funciones que hacen cosas. 
<img width="733" alt="Captura de pantalla 2020-09-30 a las 9 16 45" src="https://user-images.githubusercontent.com/57899051/94654678-af8a7400-02fd-11eb-9349-488db102a899.png">


### Archivos de funciones

Enhorabuena Juan, veo un código muy eficiente, unas funciones perfectamente documentadas. Las funciones de gráficos están parametrizadas... ¡¡¡espectacular!!

En general, la verdad es que no tengo mucho que aportar porque me parece un proyecto bastante redondo. Podrías haber hecho lo de enviarte el e-mail pero es que entiendo que lo que has hecho ha sido perfeccionar el trabajo que hacías, es decir, no veo un proyecto a lo loco queriendo avanzar, veo un proyecto redondo, con sentido, con un código súper limpio y bien documentado, así que estoy súper contenta con esto. De verdad. En plan, ojalá yo hacer un proyecto así de redondo.
¡¡Gran trabajo!! 


![neo](https://user-images.githubusercontent.com/57899051/94670872-65ac8880-0313-11eb-9156-cf502a1e8ccf.jpg)
