### ISSUE TITLE
[apis-project] Joyce Acevedo

### ISSUE THREAD

**Issue by Joycelili** [ironhack-datalabs/datamad0820#462]
https://github.com/Joycelili/Project-3

**Comment by olmocorell** [comment]
¡¡Hola Joyceeeeeeeeeeeeee!! Maifreeeeeeeeeeeeen 🚀 💪 En primerito lugar, perdona por haber venido tan tarde a corregir este proyecto. Que ya ha pasado un montón de tiempo... pero bueno ¡aquí estoy!
Vale, te cuento cositas:

### Readme 

Está casi perfect, lo único que tienes que añadir es un ejemplo completo de cómo se ejecuta el programa en plan `python3 main.py r- ratin blablabla`
Incluir esto está genial, por si alguien quiere descargarse tu repo e incluso ejecutarlo en su ordenador para probar el programa.
Por otra parte, Ojo con los enlaces, que este está caído.
<img width="921" alt="Captura de pantalla 2020-09-30 a las 12 07 12" src="https://user-images.githubusercontent.com/57899051/94672372-7a8a1b80-0315-11eb-8539-f7555ec00464.png">
Lo que sí que te falta también, aunque no es obligatorio pero es pintón, es poner el stack de tecnologías que has utilizado y poner enlaces a la documentación de dichas librerías.

### Organización de archivos

A ver, en este aspecto está bastante bien, pero yo pondría el jupyter notebook de limpieza en la carpeta de src o en una carpeta de limpieza o notebooks... así puedes tener varios, pero no lo dejaría fuera a la altura del main.
Tampoco la imagen de portada que luego metes en el readme.

### Archivos de funciones

A ver maifren ¿qué pasa aquí? No es que esté mal si te funciona, es que esas funciones hacen lo mismo, y en vez de escribir varias funciones que hacen lo mismo, escribimos una función que se puede parametrizar, y que en función del parámetro de entrada, hace una cosa u otra.... te lo explico cuando quieras si no lo entiendes ¿vale?
<img width="958" alt="Captura de pantalla 2020-09-30 a las 12 13 51" src="https://user-images.githubusercontent.com/57899051/94673041-6a267080-0316-11eb-80e6-31f69f3a8f3c.png">

Por otra parte, ojo con importar módulos que no necesitamos en los archivos de funciones ¿vale?

El main está perfect, enhorabuena.

Has hecho un muy buen trabajo Joyce, yo sé que te está costando, que has querido tirar la toalla y que le estás dando duro porque no somos desertoras y hazme caso que estoy súper orgullosa de ti. Es un placer verte evolucionar, verte escribir código cuando no sabías hacer un bucle for o lo que era una variable cuando empezó esto. Así que siéntete orgullosa.
Cualquier cosa del proyecto que quieras ver conmigo, ya sabes dónde estoy. si no es ahora, cuando tengas un poco más de tiempo. Dime¿vale?
Seguimos a tope maifreeeeeeeen

![neo](https://user-images.githubusercontent.com/57899051/94674557-a5c23a00-0318-11eb-85a7-1b166a656be1.jpg)
