### ISSUE TITLE
[apis-project] Vanessa Machuca

### ISSUE THREAD

**Issue by VanessaMacC** [ironhack-datalabs/datamad0820#463]
Hola!!! Os presento mi proyecto!
https://github.com/VanessaMacC/api-project

**Comment by ferrero-felipe** [comment]
Perfecto el argparse y la estruturación de los diferentes parametros. :)
En el readme, algo está mal en el codigo para el imagen y no sale bien. Además, me gustaria ver más información en ello, como las instruciones para ejecutar tu programa en la terminal, los diferentes parametros, etc.
Cuidado con el copy-paste de las importacioneeeeeeees. Importas un millón de cosas que no usas. :/ 
Importamos solo a lo que explicitamente se llama en ese fichero.
En el codigo, en la función main, lineas 32 y 33, tienes el nombre de 2 funciones, no las llamas. Entonces no se está haciendo nada en esas lineas. Además, toda la parte de las lineas 37 a 40 no estan en la función y se ejecutan siempre y independientemente de los parametros que se les pase. Hay que organizar la conexión entre el argparse y las diferentes funciones. Con estruturar eso, el programa funcionará bien. :)
Evita el uso del `global`, sobre todo cuando, como en ese caso, es tan sencillo como pasar el dataset como un argumento.

Buen trabajo!

![image](https://user-images.githubusercontent.com/52798316/94425307-02441e80-018c-11eb-851b-e0f3f3e31be8.png)
