### ISSUE TITLE
[apis-project] Fernando Delgado

### ISSUE THREAD

**Issue by FDELTA** [ironhack-datalabs/datamad0820#464]
https://github.com/FDELTA/apis-project.git

**Comment by ferrero-felipe** [comment]
Muy bien, Fer! :rocket:
Me encanta el gif en el readme. Jejeje
Pero no pongas todo el texto como titulares, parece un poco gritado, como cuando se escribe todo EN CAJA ALTA.
El guay de hacer programas con el argparse es que la ejecución sigue unos patrones, como los programas de la terminal. Está guay ponerlo en la documentación también. En plan:
`python3 main.py [-o COLOR_OJOS] [-p COLOR_PELO] [-s SEXO] [-g ORIENTACION_SEXUAL]`
Etc... Depende de como tengas los argumentos. `[]` para los opcionales, etc. Los mutuamente exclusivos se ponen con `( A | B )`.
Para saber exactamente como poner, lo guay es que argparse lo hace por ti y sale cuando llamas al help.
Si tienes carpetas tanto de input como de output, por que no pones el fichero `avengers.csv` en una de ellas, la que convenga.
No hace falta que se ejecute el proceso de limpieza de los datos todas las veces que ejecutes tu programa. Puedes tenerlo como un script para ejecutar a parte solo cuando tengas nuevos datos. 
Puedes poner la llamada a la funcion `superhero` en un condicional `if __name__ == “__main__"` si quieres. :)
Lo demás todo muy bien, organizado y limpio.

Muy buen trabajo.

![image](https://user-images.githubusercontent.com/52798316/94541942-7cd27400-0248-11eb-8629-8dd6ddaec266.png)
