### ISSUE TITLE
[apis-project] Laura Larrad

### ISSUE THREAD

**Issue by laura290** [ironhack-datalabs/datamad0820#465]
Buenas tardes,
https://github.com/laura290/apis-project.git

**Comment by ferrero-felipe** [comment]
Muy bien, Laura! :rocket:
Muy guay el jupyter donde analizas los datos! Super! :top:
Está genial que hagas eso aunque no fuera el objectivo explicito de ese proyecto. Cuanto mas conozcamos el domínio y la estrutura de los datos, mejor para nosotros y mejor podremos trabajar. :muscle:
Solo cuidado con los jupyters y la ejecución de las celdas para no subir por engaño un jupyter con Errores, celdas no ejecutadas, etc.
La `r` antes de un string nos sirve para identificar una expresión regular, como la `f` no sirve para cuando marcamos un string con format. Cuando tenemos un string normal, como el path para exportar un csv, no usamos esas marcaciones.
Super guay el codigo de `main.py`. Limpio y sencillo como debe ser. :grin:
![image](https://user-images.githubusercontent.com/52798316/94548777-81e7f100-0251-11eb-917b-48f50861594a.png)
Un par de cosillas sobre eso. Evita siempre que posible las variables globales. Ellas conllevan una serie de preocupaciones más que podemos evitar, sobretodo al principio cuando no tenemos tanta experiencia. Eso se resuelve escribiendo, siempre que posible, una función pura, que reciba parametros y devuelva algo. 
La segunda cosa es que al `read_csv` necesitas pasar un path de un csv, pero le estás pasando un string con un cacho de codigo python. Eso seguramente fallaria de esa manera. 
No entiendo por que en la funcion `seleccion_pais` selecionas directamente Francia y no un pais que se le pase a la función como un parámetro.
Por ultimo te comento de la organización del repo. Con que tuvieras en la raiz solo en main.py y lo demás en diferentes carpetas, se veria bastante mejor.

Buen trabajo!

![image](https://user-images.githubusercontent.com/52798316/94549623-caec7500-0252-11eb-9927-141c9e014228.png)
