### ISSUE TITLE
[apis-project] Kevin Careaga

### ISSUE THREAD

**Issue by KevsDe** [ironhack-datalabs/datamad0820#468]
https://github.com/KevsDe/apis-project

Muchas gracias por vuestros comentarios. 
![7jFH0SD](https://user-images.githubusercontent.com/66921012/93138915-227dd300-f6e0-11ea-85f1-337750ecd9f0.jpg)

**Comment by ferrero-felipe** [comment]
Muy bien, Kevin! :rocket:
No sabia de esa libreria iterations_utilities. Pandas tambien tiene una función interna ya hecha para sacar los duplicados. Si no pasas nada a ese método, te busca las filas duplicadas, pero puedes buscarlo en función de una unica columna, en ese caso seria algo como:
`df_ds[df_ds.duplicated(["Name"])]`
Y eso te devolveria todas las filas en que name fuera duplicado con alguna otra.
En lugar de borrar los datos que esten ambos los dataframe, puedes hacer un inner join, ¿no? 
Para pandas, los join se llaman `merge` y tienen un parametro `how` que se puede definir con el valor `'inner'`, además de definir `left_on, right_on` como las columnas por las cuales queremos unir los datasets, eso es, las que vayan los valores coincidentes.
![image](https://user-images.githubusercontent.com/52798316/94567859-30992b00-026c-11eb-848b-914dd51d8bb2.png)
Huele a dicionario, o como minimo una lista de tuplas.
Igualmente, no entiendo por que hacer esos cambios a las columnas. Yo creo que mantener un padron, todo en minusculas por ejemplo, y sin espacios, etc., es bastante más manejables a la hora de programar. 
Luego lo cambias solo a la hora de pintarlo al usuario. Eso es, solo como el ultimo paso del programa. Porque si no, vas a tener parte del codigo escrita con unas columnas y la otra parte con otros nombres de columna, segun les hayas escrito antes o despues de ese punto.
Interesante pensar en las diferentes posibilidades de almacenar los datos. Por ejemplo, al exportar un csv no podemos tener exactamente listas en los valores, no? Como en skills, loyalty, role, etc.
En ese caso, lo que vimos posteriormente de mongo seria mucho más util. A la vez, no seria tan directo hacer el merge.
La función correct_name podria ser el validador en el parametro `type` de  los `add_argument` en lugar de hacerlo a parte. Además estarias bastante guay y no te costaria mucho que escribieras codigo que aceptara mas de una posibilidad de escribir un mismo nombre, e.g.: Albus Dumbledore, albus dumbledore, o mismo solo dumbledore. En el ultimo caso, en que solo pusieras un apellido podrias hacer que se recogiera del dataframe todas las personas que coincidan con esa palabra, todos los potter, todos los no sé qué. En eso también entra el punto que comentamos antes de guardar la informacion segun un mismo patron y solo cambiarlo a la  hora de pintar.
En la funcion `api_related_functions.api_extraction`, en general yo prefiero que los bucles esten fuera de las funciones. Eso es, en general que escribamos una función que solo actue para un elemento y luego metemos la llamada a esa función en un bucle. Es un poco una cuestion de si consideramos todo el conjunto de los datos como un unico elementos o le consideramos un conjunto de elementos y operamos sobre cada uno.
No tireis siempre por el try...except, sobre todo cuando ambos los bloques son tan parecidos. En esa misma función `api_extraction`:
`name = {... ,  “role” = data[x].get("role","Unknown"), ...}`
Así, si no se encontra le key “role”, devuelve el valor por defecto "Unknown".

Muy buen trabajo, muy currado.

![image](https://user-images.githubusercontent.com/52798316/94571121-eade6180-026f-11eb-8d3c-e2487c49703b.png)
