### ISSUE TITLE
[apis-project] Diego Caulonga

### ISSUE THREAD

**Issue by DiegoCaulonga** [ironhack-datalabs/datamad0820#471]
Hola Felipe, que tal. Creo que el trabajo tiene todo lo que se pedía. El problema me ha venido justo al final, cuando, al ir a llamar a las argparse en la terminal, esta me dice que no sabe lo que es pandas. He mirado en internet, y me decía que tenía que actualizar y que utilizas "sudo" y demás, y teniendo en cuanto que las lio mucho con la terminal, he preferido no tocar nada y consultarte mañana este problema. De todos modos, creo que las argparse están bien formuladas. Te adjunto aqui el link de mi repo:
https://github.com/DiegoCaulonga/apis-project

**Comment by ferrero-felipe** [comment]
Muy bien, Diego!
Buen trabajo con la organización del repo, se ve un gran avanzo! Te comento apenas un equivoco conceptual. 
`src` refierese a `source code`, eso es, a codigo. No a imagenes/plots como lo que tienes en ellas. El nombre de las carpetas no es porque se necesita que hayan carpetas con esos nombres, sino que es para que tengamos las cosas organizadas. Pero si voy buscando por ficheros de codigo y encuentro solo a imagenes, algo raro pasa allí. Lo mismo para `input` y `output`, que se entiende que contendran datos. Unos de entrada, o sea, los que consumirá el programa, y los de salida que son generados por el programa. Ni siempre hay inputs o outputs.
![image](https://user-images.githubusercontent.com/52798316/94572421-49580f80-0271-11eb-9510-d3c0cc0f9cb9.png)
Las variables en minúsculaaaaaaa.
Y eso huele mucho a lista, o dicionario o algun otro contenedor de datos de ese mismo tipo.
Tienes un monton de funciones definidas al final del jupyter, lo que es un poco raro porque si las defines al final no las puedes usar. Y muchisimas de las funciones son repetidas, solo falta parametrizarlas.
No te va a funcionar exactamente el argparser. No debes tener más de un `arparse.ArgumentParser` en el programa. No tiene mucho sentido y saltaria un error seguramente, porque es como si estuvieras intentando ejecutar programas diferentes con la misma llamada, con los mismos parametros. El unico que podrias usar seria el primer de todos, que despues de ejecutarse intentaria proseguir al siguiente, que te daria un error.
Lo que quieres hacer tienes que construir con los metodos del proprio argparse, con los grupos de argumentos o con los subcomandos, como en el ejemplo que dejó Marc.
Intenta pensar en las funciones de manera más generalista y no tan específica, para que puedas parametrizarles mejor y usarlas en más de una circunstancia. Has usado muy bien las sintaxis de pandas y estoy seguro que podrias hacerlo.

Buen trabajo!

![image](https://user-images.githubusercontent.com/52798316/94549623-caec7500-0252-11eb-9927-141c9e014228.png)

**Comment by DiegoCaulonga** [comment]
Hola Felipe,
muchas gracias por la respuesta. Solo para que me quede claro cómo hay que hacerlo. He creado una función en la imagen que te adjunto, donde parametrizo las funciones que aparecen encima suyo. ¿Sería esta la manera correcta de hacerlo?
Un saludo y gracias!
________________________________
De: Felipe Ferrero <notifications@github.com>
Enviado: martes, 29 de septiembre de 2020 17:14
Para: ironhack-datalabs/datamad0820 <datamad0820@noreply.github.com>
Cc: DiegoCaulonga <diegocau@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [ironhack-datalabs/datamad0820] [apis-project] Diego Caulonga (#471)


Muy bien, Diego!
Buen trabajo con la organización del repo, se ve un gran avanzo! Te comento apenas un equivoco conceptual.
src refierese a source code, eso es, a codigo. No a imagenes/plots como lo que tienes en ellas. El nombre de las carpetas no es porque se necesita que hayan carpetas con esos nombres, sino que es para que tengamos las cosas organizadas. Pero si voy buscando por ficheros de codigo y encuentro solo a imagenes, algo raro pasa allí. Lo mismo para input y output, que se entiende que contendran datos. Unos de entrada, o sea, los que consumirá el programa, y los de salida que son generados por el programa. Ni siempre hay inputs o outputs.
[image]<https://user-images.githubusercontent.com/52798316/94572421-49580f80-0271-11eb-9510-d3c0cc0f9cb9.png>
Las variables en minúsculaaaaaaa.
Y eso huele mucho a lista, o dicionario o algun otro contenedor de datos de ese mismo tipo.
Tienes un monton de funciones definidas al final del jupyter, lo que es un poco raro porque si las defines al final no las puedes usar. Y muchisimas de las funciones son repetidas, solo falta parametrizarlas.
No te va a funcionar exactamente el argparser. No debes tener más de un arparse.ArgumentParser en el programa. No tiene mucho sentido y saltaria un error seguramente, porque es como si estuvieras intentando ejecutar programas diferentes con la misma llamada, con los mismos parametros. El unico que podrias usar seria el primer de todos, que despues de ejecutarse intentaria proseguir al siguiente, que te daria un error.
Lo que quieres hacer tienes que construir con los metodos del proprio argparse, con los grupos de argumentos o con los subcomandos, como en el ejemplo que dejó Marc.
Intenta pensar en las funciones de manera más generalista y no tan específica, para que puedas parametrizarles mejor y usarlas en más de una circunstancia. Has usado muy bien las sintaxis de pandas y estoy seguro que podrias hacerlo.

Buen trabajo!

[image]<https://user-images.githubusercontent.com/52798316/94549623-caec7500-0252-11eb-9927-141c9e014228.png>

**Comment by ferrero-felipe** [comment]
Hola Diego! No me sale el imagen así que no te lo puedo decir.  Puedes enviarmelo por slack si prefieres.
