### ISSUE TITLE
[apis-project] Gontzal Monasterio

### ISSUE THREAD

**Issue by gontzalm** [ironhack-datalabs/datamad0820#472]
https://github.com/gontzalm/books-apis

**Comment by olmocorell** [comment]
¡¡Hola Gontzaaaaaaaaaaaaaaaaal!! 🚀 💪  En primerito lugar, perdona por venir después de una semanita a corregir esto, pero.... ¡¡aquí estooooooooooooy!! 😄 
¡Te cuento!

### Readme 

Redondo, perfecto, nada que decir, de verdad. Es como se tienen que hacer los readme, con un perfecto uso del markdown, estructura, ejemplo de cómo de ejecutar el código, y las referencias con los enlaces. En fin, lo dicho. Perfecto. Hazlos todos así ¿vale? 💯 

### Organización del proyecto

Pues también perfecta.... qué pasa, ¿que he venido a decirte que todo está perfecto? Pues espero poder aportarte algo, pero de momento.... sí.

### Archivos de funciones

En primer lugar, muy bien separados los archivos de funciones por las temáticas y los nombres correspondientes y bien documentadas. También me gusta que no importes módulos a lo loco dentro de los archivos de funciones.

### Funciones

Te cuento, nuestro objetivo es hacer "funciones de propósito único". Es decir, yo creo que esto lo puedes separar en dos funciones. Una que te haga el dataframe y otra que lo limpie.
<img width="737" alt="Captura de pantalla 2020-09-20 a las 16 21 19" src="https://user-images.githubusercontent.com/57899051/93713611-52ecc380-fb5d-11ea-934b-76e781173ed3.png">

Esta función....entiendo lo que hace pero, por otra parte, también creo que se puede dividir en varias funciones y ... ¿por qué no usas el return para devolver los datos enriquecidos?
<img width="887" alt="Captura de pantalla 2020-09-20 a las 16 35 04" src="https://user-images.githubusercontent.com/57899051/93713906-3ea9c600-fb5f-11ea-8562-fc4a6a3490c3.png">

Como añadido al argparse, ¿sabes que puedes meter funciones dentro del type? te habría quedado súúúúúúúúper guay si le metes unas funciones para checkear los argparse, pues bastante epic.

Tu main.py está impecable.

Como resumen, te diré que eres un auténtico crack y que tu código está muy bien escrito, vamos, que soy súperfan. 
No tengas miedo a dividir funciones grandes en funciones más pequeñas que hagan una sola cosa y que se puedan parametrizar. Da gusto ver como evolucionas Gontzal, eres de esos alumnos que superan a los maestros y yo encantada de ver tu evolución. Muy buen trabajo y muy buen proyecto. ¡Sigue así! 💪 


![4fb5886838c0492fc4b0cee3de87b648](https://user-images.githubusercontent.com/57899051/93714027-09ea3e80-fb60-11ea-9970-92553e718b1d.jpg)
