### ISSUE TITLE
[apis-project] Jorge Alamillos

### ISSUE THREAD

**Issue by jorge-alamillos** [ironhack-datalabs/datamad0820#473]
Dejo mi link https://github.com/jorge-alamillos/apis-project.git
Soy consciente de que el código es un desastre (funciones repetidas, sin comentar, variables globales..no me ha dado tiempo a limpiarlo..de hecho no sé ni cómo puede funcionar jeje.  Me hubiera gustado hacer la parte del mail. Hay código incluido para ello que por el momento no hace nada. 

Gracias!

**Comment by ferrero-felipe** [comment]
Hola Jorge! :grin:
El readme de tu proyecto está precioso! Muy :top:
Usa el `.gitignore`. La idea de tener una carpeta de `__trash__` es que no la subas. Jajajaja
El argparse y el main estan bien definidos! Pero los validadores son absolutamente iguales, y podrian estar en otro fichero.
Un `else` con un `pass` es lo mismo que no tenerle. Jeje
Me ha gustado tu auto corrección. Es basicamente lo mismo que te habría dicho yo. Jeje
El codigo está bien en muchos puntos y se entiende todo lo que quisiste hacer, pero está un poco caos... Te faltó poder organizarle un poco mejor. Y ahora entra el punto crucial. No se trata de organizarle una vez que ya esté hecho, eso es muy difícil de hacer. El ideal es desde el principio ya escribir el codigo de la manera mas organizada posible, tomando cuidado para no hacer cosas que se pueden convertir en una bola de nieve. Jejeje

Buen trabajo asimismo.

![image](https://user-images.githubusercontent.com/52798316/94578577-34cb4580-0278-11eb-8c6c-791930bc560f.png)
