### ISSUE TITLE
[apis-project] Ana Murillo

### ISSUE THREAD

**Issue by AnaMA96** [ironhack-datalabs/datamad0820#474]
https://github.com/AnaMA96/apis-project

FPDF y yo tenemos unas cuantas charlas pendientes... perdón de antemano por el PDF, hice lo que pude 😅

**Comment by olmocorell** [comment]
¡Hola Ana! 🐒 🤛  ¿Qué tal se te dio el proyecto? Bueno, en primerito lugar, como siempre, disculpa por venir por aquí a estas alturas.... que ya ha pasado una semanita, pero bueno ... ¡¡aquí estoy!!
Te voy contando cositas 😄 🚀 

### Readme

¡Enhorabuena! Un readme que invita a seguir leyendo y a entrar dentro del proyecto, te diré que está precioso y prácticamente perfecto ¿qué me ha faltado? Pues dos cosas, una obligatoria y otra opcional...
La obligatoria, aunque me pones los argumentos que necesitamos para inializar el programa, tienes que poner también un ejemplo del código completo de cómo sería una ejecución con todos los argparse ¿vale?, dentro del readme y entre estas --> (`) comillas ```para que se vea como código```  tal que así. Bueno, si tienes dudas me dices.
La opcional, aunque bastante pintona, es meterle al readme un poco de cuento con respecto al stack de tecnologías utilizadas. En plan, para hacer esto uso python, argparse, pandas, blablabla, e incluso con algún enlace a la documentación y, sinceramente, te queda redondo. Porque al final de cara a quien venga a leer tu proyecto, es muy interesante que vea las tecnologías que manejas. 

### Organización del proyecto 

Está perfecto y limpio, en este sentido no tengo nada que decirte, la verdad....bueno, que así da gusto y que gracias por hacernos caso en ese sentido...¡Enhorabuena! 

### Archivos de funciones

A ver pequeñita.... ¡operations.py! pero si es que operations.py es lo mismo que funciones.py o misfuncioncitas.py o aquitienesmisfunciones.py o cualquiercosaqueseteocurraynodescribanada.py ... te sobra cerebrito para saber por dónde voy ¿no? 
Ponemos nombres descriptivos a los archivos de funciones para saber lo que hay dentro, quizás, en tu caso, al solo tener uno, pues te vino a la mente operations.py porque ¿cómovoyallamaryoalarchivo?, pero si entro dentro del archivo, veo que hay funciones que hacen queries a API, otras que trabajan con el dataframe.... entonces, puedes separar esos archivos, no tengas miedo a eso. Puedes tener un archivo trabajoconpandas.py requestsalaapi.py y, de nuevo, pues te coronas.

### Funciones 

Vamos a ver....
<img width="717" alt="Captura de pantalla 2020-09-20 a las 15 08 12" src="https://user-images.githubusercontent.com/57899051/93712036-1b791980-fb53-11ea-868f-42d875c54186.png">
Aunque creo que en la segunda línea de esta función tienes un error, porque ese `f importCsv():` no sé muy bien qué hace, creo que se te ha pirado.
Por otra parte.... ¡Globaaaaaaal! Vale, entiendo por qué lo haces, pero... en este caso, no necesitas hacerlo así. B
Básicamente porque, si te fijas, esta función no tiene return. Si tú haces esta función exactamente igual y pones como return temp, en el momento que tú hagas desde otro fichero `midataframe = importCsv()` la variable `midataframe`ya va a ser ese `temp`que has puesto como return en la función...
Y recuerda temp puede ser CUALQUIER COSA, es decir, puede ser ese dataframe que has obtenido a partir de la apertura del csv y al que ya has manipulado la columna de temperatura. ¿Entiendes? 
Fijo que sí, pero vamos, que si no... pues me dices 😄 
Esta función... ❤️ (es perfecta y es top)
<img width="641" alt="Captura de pantalla 2020-09-20 a las 15 33 22" src="https://user-images.githubusercontent.com/57899051/93712510-9f80d080-fb56-11ea-9e6d-7239905b3bbf.png">
Lo de los imports por doquier ya lo sabes tú.... es fácil, ve eliminando los que no necesites y ejecutando de poquito a poquito para debuggear. 
¿Esto? ¿Es para los bubbleplot?
<img width="205" alt="Captura de pantalla 2020-09-20 a las 15 38 28" src="https://user-images.githubusercontent.com/57899051/93712623-55e4b580-fb57-11ea-9df2-698ad57c0b95.png">

La función del pdf está perfect, y te digo que no está tan mal, pero uno de los problemas que puedes tener es por los gráficos, que se te exportan con mucho margen de fondo y por eso se te coloca de esa manera....en plan todo tan separado y tal.... ¿qué puedes hacer? puedes hacer un figsize de los plots antes de exportarlos o, incluso, ahora que ya sabes, y de cara al futuro, puedes manipular esas imágenes y recortarlas con pillow 😄  I D E Ó N ¿eh? Aunque, de todos modos, te digo que entiendo que fpdf a veces te coloca las cosas donde LE DA LA GANA, así que... no te perocupes, pero si quieres lo miramos ¿valep?

El main.py 😍 
Está increíble que metas funciones de checkeo en el "type" de los argparse, pero te doy un par de tips.
Ese `checkDates()` puede ir en un .py a parte de "funciones de check" por una parte...y por otra parte te digo que sería increíble si hicieras una función para checkearte todos los argparse .... 🚀 

Recapitulando un poco....¡enhorabuena! Tu proyecto está muy bien, haces lo que se te pide y con un código bastante eficiente. Hay algunas cosas que puedes refactorizar, pero no hay locuritas ni cosas horribles 😄. 
Creo que tooooodas las cosas que se pueden refactorizar te las he comentado, pero si necesitas revisar algo más en concreto...ya sabes dónde encontrarme.
Valoro mucho el esfuerzo, que hayas documentado todas las funciones...la organización, la forma de escribir el código....básicamente que cubras de manera limpia lo que se pedía en el proyecto con buen código y, por cómo son tus funciones, sé que todo lo que hay escrito en este proyecto lo entiendes y lo dominas, así que, estate contenta con tu trabajo. Porque has hecho un gran trabajo.

¡¡Espero que estés disfrutando de este finde sin proyecto!! ¡¡A por la semanaaaaaaaaaaaaa!! 💪 🚀 🐒 🤛 

![unnamed](https://user-images.githubusercontent.com/57899051/93713407-f2a95200-fb5b-11ea-8b7a-d22b04a6225b.png)
