### ISSUE TITLE
[apis-project] Miguel Gimenez

### ISSUE THREAD

**Issue by miguelgimenezgimenez** [ironhack-datalabs/datamad0820#475]
https://github.com/miguelgimenezgimenez/data-jobs

**Comment by ferrero-felipe** [comment]
Olééééé, Miguel!!!! :rocket:
Muy buen trabajo, tío! dpm.
Te has puesto las pilas y currado un montón. El resultado lo refleja, mola.
Lo unico que te comentaria ya lo tenias comentado tu diciendo que era una guarrada. Jajajaj
Gran trabajo con el webscraping via selenium. Eso es una habilidad super guay de tener en el arsenal.
Las configuraciones y colorines en la terminal son la guinda en el pastel. ;)

Super crack!

![image](https://user-images.githubusercontent.com/52798316/94668634-963ef300-0310-11eb-8fcf-dc9800141d28.png)
