### ISSUE TITLE
[apis-project] Diego Lopez-Puertas

### ISSUE THREAD

**Issue by Diegon8** [ironhack-datalabs/datamad0820#476]
https://github.com/Diegon8/Project_3-PopcornTime/tree/Project_3-PopcornTime

**Comment by ferrero-felipe** [comment]
Hola, Diego! 
Cambia la rama default de github a la donde tienes el proyecto, porque si alguien lo abre por tu github, verá la master y crerá que no hay nada.
O, mejor todavía, haz un merge de tu rama a master en el proyecto y push de master. ;)
Muy guay la documentación y las explicaciones en el jupyter.
Super guay lo de sacar los posters de la api de imdb. Super :top:!
Pero `requestIMG` y `requestART` son basicamente la misma función. Creo que con solo tener un parametro más con un valor por defecto ya resuelve.
Las carpetas son gratis para meter los jupyter, los ficheros auxiliares, etc. Jajajaja
Tienes un typo en el mutually exclusive group, un `-` donde deberia ser un `.`. No sé si será por eso que no te funcionó. 
Está en general bastante bien el codigo, pero podrias haber sido mas ambicioso, probado tener más parametros, hacer más cosas, que tu si puedes. :)

Buen trabajo!

![image](https://user-images.githubusercontent.com/52798316/94682031-a365dd00-0324-11eb-839e-0915ece1f511.png)
