### ISSUE TITLE
[apis-project] Javier Martínez

### ISSUE THREAD

**Issue by Jav1-Mart1nez** [ironhack-datalabs/datamad0820#477]
https://github.com/Jav1-Mart1nez/W4-apis-project

**Comment by ferrero-felipe** [comment]
Muy bien, Javi! :rocket:
Un monton de cosas buenas y otras mejorables que te las comentaré.
El readme, super guay! Como un detalle, donde dices `las siguientes API's`, es una unica api, lo que cambian son los parametros. ;)
Y eso nos lleva ya al fichero `web_scrapping.py`. No estás haciendo webscraping, estás sacando información de una api, que no es lo mismo.
Ese fichero está un poco caótico.... Las operaciones y peticiones que haces son solo una. Lo que cambia es un parametro. Así que pon la url en una variable, haz un dicionario con los parametros y en un bucle for, cambia el parametro `page`.
El readme está muy bien, el argparse y el repositorio super bien ordenados.
Veo que no tienes miedo de usar ficheros diferentes, pero hay extremos. Jajajaja
No hace falta un fichero para max, otro para min, otro para sum, otro para no se que... Pero eso, la justa medida, se va adquiriendo con el tiempo. 
Peeeeeeeeeeeeeero Mucho cuidado con esas funciones que devuelven print, pues print devuelve None.

Muy buen trabajo!

P.D.: Como alguien que empezó a jugar Breath of the Wild recentemente, estoy de acuerdo con la conclusión. Jajaja

![image](https://user-images.githubusercontent.com/52798316/94684552-80d5c300-0328-11eb-97d6-8b28d6e6187e.png)
